version: "3.8"

# CREATE TWO CONTAINERS FROM SAME IMAGE
services:
  docker-backend-1:
    image: docker-backend
    container_name: docker-backend-1
    restart: always
    build: .
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
  docker-backend-2:
    image: docker-backend
    container_name: docker-backend-2
    restart: always
    build: .
    ports:
      - "5001:5000"
